#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# deploy_worker.sh – Set up ONE WORKER VM
#
# Installs only Python + the project deps (Redis/RabbitMQ live on the broker
# VM, not here), points the worker at the central broker, and registers it as
# a systemd service so it starts on boot and auto-restarts on crash.
#
# Run this on EACH worker VM, after copying the project to it.
#
# Usage:
#   chmod +x scripts/deploy_worker.sh
#   sudo BROKER_HOST=<broker-private-ip> ./scripts/deploy_worker.sh
#
# Required:
#   BROKER_HOST      private IP of the broker VM (Redis + RabbitMQ)
#
# Optional overrides (env vars):
#   RABBITMQ_USER    (default: ticket)   must match deploy_broker.sh
#   RABBITMQ_PASS    (default: ticket)
#   REDIS_PASSWORD   (default: empty)    set only if the broker has one
#   WORKER_ID        (default: hostname) node name in the metrics
#   PREFETCH         (default: 10)       RabbitMQ prefetch per worker
#   INSTANCES        (default: 1)        worker processes to run on this VM
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

BROKER_HOST="${BROKER_HOST:?Set BROKER_HOST to the broker VM private IP}"
RMQ_USER="${RABBITMQ_USER:-ticket}"
RMQ_PASS="${RABBITMQ_PASS:-ticket}"
REDIS_PASS="${REDIS_PASSWORD:-}"
WORKER_ID="${WORKER_ID:-$(hostname)}"
PREFETCH="${PREFETCH:-10}"
INSTANCES="${INSTANCES:-1}"
RUN_USER="${SUDO_USER:-ubuntu}"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

echo "═══════════════════════════════════════════════════"
echo "  Concert Ticket System – WORKER VM Setup"
echo "  Broker: $BROKER_HOST   Worker id: $WORKER_ID   Instances: $INSTANCES"
echo "═══════════════════════════════════════════════════"

# ── 1. Python + deps ────────────────────────────────────────────────
echo "[1/4] Installing Python dependencies…"
apt-get update -qq
apt-get install -y -qq python3 python3-pip
# A worker only needs pika (RabbitMQ) + redis, so install just those instead
# of the full requirements.txt (fastapi/matplotlib/… are not used here and
# their upgrades clash with Debian-managed packages on Ubuntu 24.04).
# Ubuntu 24.04+ marks the system Python "externally managed" (PEP 668), so we
# pass --break-system-packages to install system-wide on this throwaway lab VM
# (the systemd unit runs /usr/bin/python3, which then finds these packages).
python3 -m pip install --break-system-packages pika redis

# ── 2. Environment file (read by the systemd unit) ──────────────────
echo "[2/4] Writing /etc/ticket-worker.env…"
cat > /etc/ticket-worker.env <<EOF
# Generated by deploy_worker.sh – points this worker at the broker VM.
REDIS_HOST=$BROKER_HOST
REDIS_PORT=6379
REDIS_PASSWORD=$REDIS_PASS
RABBITMQ_HOST=$BROKER_HOST
RABBITMQ_PORT=5672
RABBITMQ_USER=$RMQ_USER
RABBITMQ_PASS=$RMQ_PASS
WORKER_ID=$WORKER_ID
PREFETCH=$PREFETCH
PYTHONPATH=$PROJECT_DIR
EOF

# ── 3. Install the systemd template unit ────────────────────────────
echo "[3/4] Installing systemd service…"
sed -e "s#__PROJECT_DIR__#$PROJECT_DIR#g" \
    -e "s#^User=ubuntu#User=$RUN_USER#" \
    "$SCRIPT_DIR/ticket-worker@.service" \
    > /etc/systemd/system/ticket-worker@.service
systemctl daemon-reload

# ── 4. Start the requested number of worker instances ───────────────
echo "[4/4] Starting $INSTANCES worker instance(s)…"
for i in $(seq 1 "$INSTANCES"); do
    systemctl enable --now "ticket-worker@$i"
done

echo ""
echo "═══════════════════════════════════════════════════"
echo "  Worker VM ready."
echo "  Status : sudo systemctl status 'ticket-worker@*'"
echo "  Logs   : sudo journalctl -u 'ticket-worker@1' -f"
echo "  Stop   : sudo systemctl stop  'ticket-worker@1'   (test fault tolerance)"
echo "  Start  : sudo systemctl start 'ticket-worker@1'"
echo "═══════════════════════════════════════════════════"
